// Generated by gencpp from file lab3/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_ADDTWOINTS_H
#define LAB3_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <lab3/AddTwoIntsRequest.h>
#include <lab3/AddTwoIntsResponse.h>


namespace lab3
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace lab3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab3::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::lab3::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::lab3::AddTwoInts > {
  static const char* value()
  {
    return "lab3/AddTwoInts";
  }

  static const char* value(const ::lab3::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::lab3::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::lab3::AddTwoInts >
template<>
struct MD5Sum< ::lab3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::AddTwoInts >::value();
  }
  static const char* value(const ::lab3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::AddTwoIntsRequest> should match
// service_traits::DataType< ::lab3::AddTwoInts >
template<>
struct DataType< ::lab3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::lab3::AddTwoInts >::value();
  }
  static const char* value(const ::lab3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab3::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::lab3::AddTwoInts >
template<>
struct MD5Sum< ::lab3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::AddTwoInts >::value();
  }
  static const char* value(const ::lab3::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::AddTwoIntsResponse> should match
// service_traits::DataType< ::lab3::AddTwoInts >
template<>
struct DataType< ::lab3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::lab3::AddTwoInts >::value();
  }
  static const char* value(const ::lab3::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB3_MESSAGE_ADDTWOINTS_H
