(cl:defpackage lab3-msg
  (:use )
  (:export
   "<COUNTERACTION>"
   "COUNTERACTION"
   "<COUNTERACTIONFEEDBACK>"
   "COUNTERACTIONFEEDBACK"
   "<COUNTERACTIONGOAL>"
   "COUNTERACTIONGOAL"
   "<COUNTERACTIONRESULT>"
   "COUNTERACTIONRESULT"
   "<COUNTERFEEDBACK>"
   "COUNTERFEEDBACK"
   "<COUNTERGOAL>"
   "COUNTERGOAL"
   "<COUNTERRESULT>"
   "COUNTERRESULT"
  ))

